blank_issues_enabled: false
contact_links:
  - name: "Have a question?"
    url: https://github.com/abraunegg/onedrive/discussions
    about: "Please do not raise a GitHub issue for asking questions. Post a question in discussions. Thanks in advance for helping us keep the issue tracker clean!"